- hosts: all
  vars:
    packages:
      - apache2
      - tree
      - unzip
  become: yes
  tasks:
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    register: hello
    ignore_errors: yes  
  - debug: msg={{ hello }}
